version: 1
directus: 11.4.0
vendor: sqlite
collections:
  - collection: artists
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: artists
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: artists
  - collection: exhibitions
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: exhibitions
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
      versioning: false
    schema:
      name: exhibitions
fields:
  - collection: artists
    field: id
    type: integer
    meta:
      collection: artists
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: artists
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: artists
    field: date_created
    type: timestamp
    meta:
      collection: artists
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 2
      special:
        - date-created
        - cast-timestamp
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: artists
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: artists
    field: date_updated
    type: timestamp
    meta:
      collection: artists
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-updated
        - cast-timestamp
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: artists
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: artists
    field: name
    type: string
    meta:
      collection: artists
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: name
      table: artists
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: exhibitions
      foreign_key_column: id
  - collection: exhibitions
    field: id
    type: integer
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: exhibitions
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: status
    type: string
    meta:
      collection: exhibitions
      conditions: null
      display: labels
      display_options:
        choices:
          - background: var(--theme--primary-background)
            color: var(--theme--primary)
            foreground: var(--theme--primary)
            text: $t:published
            value: published
          - background: var(--theme--background-normal)
            color: var(--theme--foreground)
            foreground: var(--theme--foreground)
            text: $t:draft
            value: draft
          - background: var(--theme--warning-background)
            color: var(--theme--warning)
            foreground: var(--theme--warning)
            text: $t:archived
            value: archived
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - color: var(--theme--primary)
            text: $t:published
            value: published
          - color: var(--theme--foreground)
            text: $t:draft
            value: draft
          - color: var(--theme--warning)
            text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: status
      table: exhibitions
      data_type: varchar
      default_value: draft
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: date_created
    type: timestamp
    meta:
      collection: exhibitions
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-created
        - cast-timestamp
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: exhibitions
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: date_updated
    type: timestamp
    meta:
      collection: exhibitions
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-updated
        - cast-timestamp
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: exhibitions
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: start_date
    type: date
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: start_date
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: start_date
      table: exhibitions
      data_type: date
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: end_date
    type: date
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: end_date
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: end_date
      table: exhibitions
      data_type: date
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: address
    type: string
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: address
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 7
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: address
      table: exhibitions
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: exhibitions
    field: artist
    type: alias
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: artist
      group: null
      hidden: false
      interface: list-o2m
      note: null
      options:
        sort: null
      readonly: false
      required: true
      sort: 8
      special:
        - o2m
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: exhibitions
    field: curator
    type: integer
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: curator
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options: {}
      readonly: false
      required: true
      sort: 9
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: curator
      table: exhibitions
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: artists
      foreign_key_column: id
  - collection: exhibitions
    field: description
    type: text
    meta:
      collection: exhibitions
      conditions: null
      display: null
      display_options: null
      field: description
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options:
        font: monospace
      readonly: false
      required: true
      sort: 10
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: description
      table: exhibitions
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations:
  - collection: artists
    field: name
    related_collection: exhibitions
    meta:
      junction_field: null
      many_collection: artists
      many_field: name
      one_allowed_collections: null
      one_collection: exhibitions
      one_collection_field: null
      one_deselect_action: nullify
      one_field: artist
      sort_field: null
    schema:
      table: artists
      column: name
      foreign_key_table: exhibitions
      foreign_key_column: id
      constraint_name: null
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: exhibitions
    field: curator
    related_collection: artists
    meta:
      junction_field: null
      many_collection: exhibitions
      many_field: curator
      one_allowed_collections: null
      one_collection: artists
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: exhibitions
      column: curator
      foreign_key_table: artists
      foreign_key_column: id
      constraint_name: null
      on_update: NO ACTION
      on_delete: SET NULL
